import React, { useState, useMemo } from 'react';
import { CircleDot, Sparkles, CalendarDays, X } from 'lucide-react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { showSuccessToast, showErrorToast } from '../../../../utils/toast';
import { createCouponAPI } from '../../../../apis/admin/coupon';

const initialFormState = {
  description: '',
  startDate: '',
  expirationDate: '',
  discountType: '',
  discountValue: '',
  usageLimit: '',
  maxDiscount: '',
  minOrderAmount: '',
};

const CreateCouponForm = ({ onSuccess }) => {
  const queryClient = useQueryClient();
  const [formData, setFormData] = useState(initialFormState);
  const [isSubmitting, setIsSubmitting] = useState(false);

    // Dynamic validation constants
  const tzoffset = new Date().getTimezoneOffset() * 60000;
  const currentDateTime = new Date(Date.now() - tzoffset).toISOString().slice(0, 16);
  const minExpiration = formData.startDate ? formData.startDate : currentDateTime;

  const canCreateCoupon = useMemo(() => {
    const start = new Date(formData.startDate);
    const end = new Date(formData.expirationDate);
    const now = new Date();
    
    return (
      formData.startDate.trim().length > 0
      && formData.expirationDate.trim().length > 0
      && formData.discountType.trim().length > 0
      && formData.discountValue.toString().trim().length > 0
      && start >= new Date(now.setSeconds(0,0))
      && end > start
    );
  }, [formData]);

  const updateField = (event) => {
    const { name, value } = event.target;
    setFormData((currentState) => ({ ...currentState, [name]: value }));
  };

  const handleCreateSubmit = async (event) => {
    event.preventDefault();
    if (!canCreateCoupon) return;

    try {
      setIsSubmitting(true);
      const payload = {
        description: formData.description,
        discountType: formData.discountType === 'percentage' ? 'PERCENT' : 'FIXED',
        discountValue: parseFloat(formData.discountValue),
        minOrderAmount: formData.minOrderAmount ? parseFloat(formData.minOrderAmount) : null,
        maxDiscount: formData.maxDiscount ? parseFloat(formData.maxDiscount) : null,
        startDate: formData.startDate,
        expirationDate: formData.expirationDate,
        usageLimit: (!formData.usageLimit && !formData.customUsageLimit) ? null : 
                    formData.usageLimit === 'custom' ? parseInt(formData.customUsageLimit) : parseInt(formData.usageLimit),
      };

      const newCoupon = await createCouponAPI(payload);
      showSuccessToast(`Coupon ${newCoupon.code} has been created successfully.`);
      setFormData(initialFormState);
      queryClient.invalidateQueries({ queryKey: ['coupons'] });
      
      if (onSuccess) {
        onSuccess();
      }
    } catch (error) {
      showErrorToast(error.message || 'Failed to create coupon');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="rounded-[1.5rem] border border-gray-100 bg-white p-5 lg:p-8 shadow-sm">
      <form
        onSubmit={handleCreateSubmit}
        className="max-w-4xl"
      >
        <div className="flex items-center gap-3 mb-8 pb-4 border-b border-gray-100">
          <div className="w-8 h-8 rounded-full bg-orange-50 flex items-center justify-center">
            <CircleDot size={16} className="text-orange-500" />
          </div>
          <h2 className="text-base font-bold text-gray-900">Basic Information</h2>
        </div>

        <div className="space-y-5">
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-2">Coupon Code</label>
            <div className="flex flex-col gap-2 md:flex-row md:items-center">
              <input
                type="text"
                disabled
                placeholder="Auto-generated upon creation"
                className="w-full rounded-2xl border border-gray-200 bg-gray-100 px-4 py-3 text-sm text-gray-500 outline-none cursor-not-allowed"
              />
              <div className="shrink-0 inline-flex items-center justify-center gap-2 rounded-xl border border-gray-200 bg-gray-50 px-4 py-2.5 text-sm font-semibold text-gray-500 cursor-not-allowed">
                <Sparkles size={16} className="text-gray-400" />
                Auto-Generated
              </div>
            </div>
            <p className="mt-1 text-xs text-gray-500">The code will be securely generated by the system.</p>
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-2">Description</label>
            <input
              type="text"
              name="description"
              value={formData.description}
              onChange={updateField}
              placeholder="e.g. 10% off for all orders"
              className="w-full rounded-2xl border border-gray-200 bg-gray-50/50 px-4 py-3 text-sm text-gray-700 outline-none transition focus:border-orange-300 focus:ring-4 focus:ring-orange-50"
            />
          </div>

          <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Start Date</label>
              <div className="relative">
                <CalendarDays size={16} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
                <input type="datetime-local"
                        name="startDate"
                        value={formData.startDate}
                        min={currentDateTime}
                  onChange={updateField}
                  className="w-full rounded-2xl border border-gray-200 bg-gray-50/50 pl-11 pr-4 py-3 text-sm text-gray-700 outline-none transition focus:border-orange-300 focus:ring-4 focus:ring-orange-50"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Expiration Date</label>
              <div className="relative">
                <CalendarDays size={16} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
                <input type="datetime-local"
                        name="expirationDate"
                        value={formData.expirationDate}
                        min={minExpiration}
                  onChange={updateField}
                  className="w-full rounded-2xl border border-gray-200 bg-gray-50/50 pl-11 pr-4 py-3 text-sm text-gray-700 outline-none transition focus:border-orange-300 focus:ring-4 focus:ring-orange-50"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Discount Type</label>
              <select
                name="discountType"
                value={formData.discountType}
                onChange={updateField}
                className="w-full cursor-pointer appearance-none rounded-2xl border border-gray-200 bg-gray-50/50 px-4 py-3 text-sm text-gray-700 outline-none transition focus:border-orange-300 focus:ring-4 focus:ring-orange-50"
              >
                <option value="">Choose Discount Type</option>
                <option value="percentage">Percentage</option>
                <option value="fixed-amount">Fixed Amount</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Discount Value</label>
              <input
                type="number"
                min="0"
                step="0.01"
                name="discountValue"
                value={formData.discountValue}
                onChange={updateField}
                placeholder="Enter Discount Value"
                className="w-full rounded-2xl border border-gray-200 bg-gray-50/50 px-4 py-3 text-sm text-gray-700 placeholder-gray-400 outline-none transition focus:border-orange-300 focus:ring-4 focus:ring-orange-50"
              />
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Usage Limit</label>
              {formData.usageLimit === 'custom' ? (
                <div className="relative">
                  <input
                    type="number"
                    min="1"
                    name="usageLimit"
                    value={formData.customUsageLimit || ''}
                    onChange={e => updateField({ target: { name: 'customUsageLimit', value: e.target.value } })}
                    placeholder="Enter custom limit"
                    className="w-full rounded-2xl border border-gray-200 bg-gray-50/50 px-4 py-3 pr-10 text-sm text-gray-700 outline-none transition focus:border-orange-300 focus:ring-4 focus:ring-orange-50"
                    autoFocus
                  />
                  <button 
                    type="button" 
                    onClick={() => {
                      updateField({ target: { name: 'usageLimit', value: '' } });
                      updateField({ target: { name: 'customUsageLimit', value: '' } });
                    }}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                    title="Cancel custom limit"
                  >
                    <X size={16} />
                  </button>
                </div>
              ) : (
                <select
                  name="usageLimit"
                  value={formData.usageLimit}
                  onChange={updateField}
                  className="w-full cursor-pointer appearance-none rounded-2xl border border-gray-200 bg-gray-50/50 px-4 py-3 text-sm text-gray-700 outline-none transition focus:border-orange-300 focus:ring-4 focus:ring-orange-50"
                >
                  <option value="">Unlimited (Leave Empty)</option>
                  <option value="50">50</option>
                  <option value="100">100</option>
                  <option value="1000">1000</option>
                  <option value="custom">Custom...</option>
                </select>
              )}
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Max Discount Amount (Optional)</label>
              <div className="relative">
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  name="maxDiscount"
                  value={formData.maxDiscount}
                  onChange={updateField}
                  placeholder="No Limit"
                  className="w-full rounded-2xl border border-gray-200 bg-gray-50/50 px-4 py-3 pr-8 text-sm text-gray-700 outline-none transition focus:border-orange-300 focus:ring-4 focus:ring-orange-50"
                />
                <span className="absolute right-4 top-1/2 -translate-y-1/2 text-xs text-gray-400 font-medium">Rs.</span>
              </div>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Minimum Order Amount (Optional)</label>
              <div className="relative">
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  name="minOrderAmount"
                  value={formData.minOrderAmount}
                  onChange={updateField}
                  placeholder="0.00"
                  className="w-full rounded-2xl border border-gray-200 bg-gray-50/50 px-4 py-3 pr-8 text-sm text-gray-700 outline-none transition focus:border-orange-300 focus:ring-4 focus:ring-orange-50"
                />
                <span className="absolute right-4 top-1/2 -translate-y-1/2 text-xs text-gray-400 font-medium">Rs.</span>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-8 flex justify-end border-t border-gray-100 pt-6">
          <button
            type="submit"
            disabled={!canCreateCoupon || isSubmitting}
            className="inline-flex items-center justify-center rounded-xl bg-orange-500 px-6 py-2.5 text-sm font-semibold text-white shadow-md shadow-orange-200 transition hover:bg-orange-600 disabled:cursor-not-allowed disabled:opacity-70"
          >
            {isSubmitting ? 'Creating...' : 'Create Coupon'}
          </button>
        </div>
      </form>
    </div>
  );
};

export default CreateCouponForm;



