import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { 
  ArrowLeft, Download, RefreshCw, Trash2, QrCode, AlertTriangle 
} from 'lucide-react';
import AdminSidebar from '../components/admin/AdminSidebar';
import AdminHeader from '../components/admin/AdminHeader';
import { 
  getActiveQrCodeAPI, createQrCodeAPI, 
  regenerateQrCodeAPI, revokeQrCodeAPI, downloadQrCodeAPI 
} from '../apis/admin/table';

export default function TableQrPage() {
  const { tableId } = useParams();
  const navigate = useNavigate();

  const [qrData, setQrData] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    fetchActiveQrCode();
  }, [tableId]);

  const fetchActiveQrCode = async () => {
    setIsLoading(true);
    setError('');
    try {
      const data = await getActiveQrCodeAPI(tableId);
      setQrData(data);
    } catch (err) {
      if (err.message.includes('No active QR code found')) {
        setQrData(null); // It's fine if not found
      } else {
        setError(err.message || 'Failed to fetch QR code.');
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerate = async () => {
    setIsProcessing(true);
    setError('');
    try {
      const data = await createQrCodeAPI(tableId);
      setQrData(data);
    } catch (err) {
      setError(err.message || 'Failed to generate QR code.');
    } finally {
      setIsProcessing(false);
    }
  };

  const handleRegenerate = async () => {
    if (!qrData?.id) return;
    if (!window.confirm("Are you sure you want to regenerate the QR code? The old one will be revoked.")) return;
    
    setIsProcessing(true);
    setError('');
    try {
      const data = await regenerateQrCodeAPI(qrData.id, "Regenerated by Admin");
      setQrData(data);
    } catch (err) {
      setError(err.message || 'Failed to regenerate QR code.');
    } finally {
      setIsProcessing(false);
    }
  };

  const handleDelete = async () => {
    if (!qrData?.id) return;
    if (!window.confirm("Are you sure you want to delete (revoke) this QR code?")) return;

    setIsProcessing(true);
    setError('');
    try {
      await revokeQrCodeAPI(qrData.id, "Revoked by Admin");
      setQrData(null);
    } catch (err) {
      setError(err.message || 'Failed to delete QR code.');
    } finally {
      setIsProcessing(false);
    }
  };

  const handleDownload = async () => {
    if (!qrData?.id) return;
    try {
      const blob = await downloadQrCodeAPI(qrData.id);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `table-${tableId}-qr.png`;
      a.click();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      setError(err.message || 'Failed to download QR code.');
    }
  };

  return (
    <div className="flex h-screen bg-[#F8F9FA] font-sans">
      <AdminSidebar activePage="/admin/tables" />

      <main className="flex-1 flex flex-col h-screen overflow-hidden bg-[#FAFAFA]">
        <AdminHeader />

        <div className="flex-1 overflow-y-auto px-10 pb-10">
          <div className="flex items-center justify-between mb-8 mt-4">
            <div className="flex items-center gap-4">
              <button
                onClick={() => navigate('/admin/tables')}
                className="w-10 h-10 flex items-center justify-center rounded-xl bg-white border border-gray-200 text-gray-500 hover:bg-gray-50 hover:text-gray-700 transition-colors shadow-sm"
              >
                <ArrowLeft size={20} />
              </button>
              <div>
                <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Table {tableId} QR Code</h1>
                <p className="text-gray-500 text-sm mt-1">Manage the ordering QR code for this table</p>
              </div>
            </div>
          </div>

          {error && (
            <div className="mb-6 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
              <AlertTriangle size={18} />
              {error}
            </div>
          )}

          <div className="max-w-2xl mx-auto">
            <div className="bg-white rounded-[1.5rem] border border-gray-100 shadow-sm p-8 text-center flex flex-col items-center">
              
              {isLoading ? (
                <div className="py-20 text-gray-400">Loading...</div>
              ) : qrData ? (
                <>
                  <div className="bg-gray-50 p-6 rounded-2xl border border-gray-100 mb-8 inline-block shadow-inner">
                    <img 
                      src={`data:image/png;base64,${qrData.qrImageBase64}`} 
                      alt="Table QR Code" 
                      className="w-64 h-64 object-contain rounded-xl bg-white p-2 shadow-sm"
                    />
                  </div>
                  
                  <div className="flex items-center justify-center gap-4 flex-wrap w-full max-w-md">
                    <button
                      onClick={handleDownload}
                      disabled={isProcessing}
                      className="flex-1 flex items-center justify-center gap-2 bg-[#FFFBF7] border border-orange-200 text-orange-600 hover:bg-orange-50 px-5 py-3 rounded-xl font-semibold text-sm transition-colors disabled:opacity-50"
                    >
                      <Download size={18} />
                      Download
                    </button>
                    
                    <button
                      onClick={handleRegenerate}
                      disabled={isProcessing}
                      className="flex-1 flex items-center justify-center gap-2 bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 px-5 py-3 rounded-xl font-semibold text-sm transition-colors disabled:opacity-50"
                    >
                      <RefreshCw size={18} />
                      Regenerate
                    </button>
                    
                    <button
                      onClick={handleDelete}
                      disabled={isProcessing}
                      className="w-full flex items-center justify-center gap-2 bg-red-50 border border-red-100 text-red-600 hover:bg-red-100 px-5 py-3 rounded-xl font-semibold text-sm transition-colors disabled:opacity-50"
                    >
                      <Trash2 size={18} />
                      Delete
                    </button>
                  </div>
                </>
              ) : (
                <div className="py-16 flex flex-col items-center text-center">
                  <div className="w-20 h-20 bg-orange-50 text-orange-500 rounded-full flex items-center justify-center mb-4">
                    <QrCode size={40} />
                  </div>
                  <h2 className="text-xl font-bold text-gray-900 mb-2">No QR Code Found</h2>
                  <p className="text-gray-500 mb-8 max-w-sm text-sm">
                    This table currently does not have an active QR code for ordering. Generate one to allow customers to scan and order.
                  </p>
                  <button
                    onClick={handleGenerate}
                    disabled={isProcessing}
                    className="bg-[#FF6B00] hover:bg-[#e66000] text-white px-8 py-3 rounded-xl font-semibold text-sm shadow-md shadow-orange-500/20 transition-all disabled:opacity-50"
                  >
                    {isProcessing ? 'Generating...' : 'Generate QR Code'}
                  </button>
                </div>
              )}

            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
