import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { 
  ArrowLeft, Download, RefreshCw, Trash2, QrCode, AlertTriangle 
} from 'lucide-react';

import { 
  getActiveQrCodeAPI, createQrCodeAPI, 
  regenerateQrCodeAPI, revokeQrCodeAPI, downloadQrCodeAPI, getTableByIdAPI
} from '../../apis/admin/table';
import { showSuccessToast, showErrorToast } from '../../utils/toast';

// Admin page for table-specific QR generation and lifecycle controls.
export default function TableQrPage() {
  const { tableId } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [error, setError] = useState('');
  const [confirmModal, setConfirmModal] = useState({ isOpen: false, action: null, title: '', message: '', type: 'warning' });

  const { data: tableData } = useQuery({
    queryKey: ['table', tableId],
    queryFn: () => getTableByIdAPI(tableId),
  });

  const { data: qrData, isLoading } = useQuery({
    queryKey: ['qrCode', tableId],
    queryFn: async () => {
      try {
        return await getActiveQrCodeAPI(tableId);
      } catch (err) {
        if (err.message.includes('No active QR code found') || err.message.includes('Unable to get active QR code')) {
          return null;
        }
        throw err;
      }
    },
    retry: false,
  });

  const generateMutation = useMutation({
    mutationFn: () => createQrCodeAPI(tableId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['qrCode', tableId] });
      setError('');
      showSuccessToast('QR code generated successfully');
    },
    onError: (err) => {
      setError(err.message || 'Failed to generate QR code.');
      showErrorToast(err.message || 'Failed to generate QR code.');
    }
  });

  const regenerateMutation = useMutation({
    mutationFn: (id) => regenerateQrCodeAPI(id, "Regenerated by Admin"),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['qrCode', tableId] });
      setError('');
      showSuccessToast('QR code regenerated successfully');
    },
    onError: (err) => {
      setError(err.message || 'Failed to regenerate QR code.');
      showErrorToast(err.message || 'Failed to regenerate QR code.');
    }
  });

  const deleteMutation = useMutation({
    mutationFn: (id) => revokeQrCodeAPI(id, "Revoked by Admin"),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['qrCode', tableId] });
      setError('');
      showSuccessToast('QR code deleted successfully');
    },
    onError: (err) => {
      setError(err.message || 'Failed to delete QR code.');
      showErrorToast(err.message || 'Failed to delete QR code.');
    }
  });

  const isProcessing = generateMutation.isPending || regenerateMutation.isPending || deleteMutation.isPending;

  const handleGenerate = () => generateMutation.mutate();

  const handleRegenerate = () => {
    if (!qrData?.id) return;
    setConfirmModal({
      isOpen: true,
      action: 'regenerate',
      title: 'Regenerate QR Code?',
      message: 'Are you sure you want to regenerate the QR code? The old one will be revoked.',
      type: 'warning'
    });
  };

  const handleDelete = () => {
    if (!qrData?.id) return;
    setConfirmModal({
      isOpen: true,
      action: 'delete',
      title: 'Delete QR Code?',
      message: 'Are you sure you want to delete (revoke) this QR code? It will no longer be valid for ordering.',
      type: 'danger'
    });
  };

  const confirmAction = () => {
    if (confirmModal.action === 'regenerate') {
      regenerateMutation.mutate(qrData.id);
    } else if (confirmModal.action === 'delete') {
      deleteMutation.mutate(qrData.id);
    }
    setConfirmModal({ isOpen: false, action: null, title: '', message: '', type: 'warning' });
  };

  const handleDownload = async () => {
    if (!qrData?.id) return;
    try {
      const blob = await downloadQrCodeAPI(qrData.id);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `table-${tableId}-qr.png`;
      a.click();
      window.URL.revokeObjectURL(url);
      showSuccessToast('QR code downloaded successfully');
    } catch (err) {
      setError(err.message || 'Failed to download QR code.');
      showErrorToast(err.message || 'Failed to download QR code.');
    }
  };

  return (
    <div className="bg-[#FAFAFA] font-sans px-10 pb-10">
          <div className="flex items-center justify-between mb-8 mt-4">
            <div className="flex items-center gap-4">
              <button
                onClick={() => navigate('/admin/tables')}
                className="w-10 h-10 flex items-center justify-center rounded-xl bg-white border border-gray-200 text-gray-500 hover:bg-gray-50 hover:text-gray-700 transition-colors shadow-sm"
              >
                <ArrowLeft size={20} />
              </button>
              <div>
                <h1 className="text-2xl font-bold text-gray-900 tracking-tight">
                  Table {tableData?.tableNumber || tableId} (ID: {tableId}) QR Code
                </h1>
                <p className="text-gray-500 text-sm mt-1">Manage the ordering QR code for this table</p>
              </div>
            </div>
          </div>

          {error && (
            <div className="mb-6 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
              <AlertTriangle size={18} />
              {error}
            </div>
          )}

          <div className="max-w-2xl mx-auto">
            <div className="bg-white rounded-[1.5rem] border border-gray-100 shadow-sm p-8 text-center flex flex-col items-center">
              
              {isLoading ? (
                <div className="py-20 text-gray-400">Loading...</div>
              ) : qrData ? (
                <>
                  <div className="bg-gray-50 p-6 rounded-2xl border border-gray-100 mb-8 inline-block shadow-inner">
                    <img 
                      src={`data:image/png;base64,${qrData.qrImageBase64}`} 
                      alt="Table QR Code" 
                      className="w-64 h-64 object-contain rounded-xl bg-white p-2 shadow-sm"
                    />
                  </div>
                  
                  <div className="flex items-center justify-center gap-4 flex-wrap w-full max-w-md">
                    <button
                      onClick={handleDownload}
                      disabled={isProcessing}
                      className="flex-1 flex items-center justify-center gap-2 bg-[#FFFBF7] border border-orange-200 text-orange-600 hover:bg-orange-50 px-5 py-3 rounded-xl font-semibold text-sm transition-colors disabled:opacity-50"
                    >
                      <Download size={18} />
                      Download
                    </button>
                    
                    <button
                      onClick={handleRegenerate}
                      disabled={isProcessing}
                      className="flex-1 flex items-center justify-center gap-2 bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 px-5 py-3 rounded-xl font-semibold text-sm transition-colors disabled:opacity-50"
                    >
                      <RefreshCw size={18} />
                      Regenerate
                    </button>
                    
                    <button
                      onClick={handleDelete}
                      disabled={isProcessing}
                      className="w-full flex items-center justify-center gap-2 bg-red-50 border border-red-100 text-red-600 hover:bg-red-100 px-5 py-3 rounded-xl font-semibold text-sm transition-colors disabled:opacity-50"
                    >
                      <Trash2 size={18} />
                      Delete
                    </button>
                  </div>
                </>
              ) : (
                <div className="py-16 flex flex-col items-center text-center">
                  <div className="w-20 h-20 bg-orange-50 text-orange-500 rounded-full flex items-center justify-center mb-4">
                    <QrCode size={40} />
                  </div>
                  <h2 className="text-xl font-bold text-gray-900 mb-2">No QR Code Found</h2>
                  <p className="text-gray-500 mb-8 max-w-sm text-sm">
                    This table currently does not have an active QR code for ordering. Generate one to allow customers to scan and order.
                  </p>
                  <button
                    onClick={handleGenerate}
                    disabled={isProcessing}
                    className="bg-[#FF6B00] hover:bg-[#e66000] text-white px-8 py-3 rounded-xl font-semibold text-sm shadow-md shadow-orange-500/20 transition-all disabled:opacity-50"
                  >
                    {isProcessing ? 'Generating...' : 'Generate QR Code'}
                  </button>
                </div>
              )}

            </div>
          </div>

      {/* Confirmation Modal */}
      {confirmModal.isOpen && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-[1.5rem] w-full max-w-sm p-6 shadow-xl text-center">
            <div className={`mx-auto w-16 h-16 rounded-full flex items-center justify-center mb-4 ${confirmModal.type === 'danger' ? 'bg-red-50 text-red-500' : 'bg-orange-50 text-orange-500'}`}>
              <AlertTriangle size={32} />
            </div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">{confirmModal.title}</h2>
            <p className="text-gray-500 text-sm mb-8">{confirmModal.message}</p>
            <div className="flex gap-3">
              <button
                onClick={() => setConfirmModal({ isOpen: false, action: null, title: '', message: '', type: 'warning' })}
                className="flex-1 px-5 py-3 rounded-xl text-sm font-semibold text-gray-600 bg-gray-100 hover:bg-gray-200 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={confirmAction}
                className={`flex-1 px-5 py-3 rounded-xl text-sm font-semibold text-white transition-colors ${confirmModal.type === 'danger' ? 'bg-red-600 hover:bg-red-700' : 'bg-[#FF6B00] hover:bg-[#e66000]'}`}
              >
                Confirm
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
